backend:
  name: github
  repo: thomas-claireau/my-portfolio
  branch: master
  base_url: https://my-portfolio-kappa-gray.vercel.app
  auth_endpoint: /api/auth
media_folder: public/img
public_folder: img
i18n:
  structure: single_file
  locales: [en, fr]
collections:
  - name: "pages"
    label: "Pages"
    i18n: true
    files:
      - label: "Accueil"
        name: "accueil"
        file: "content/pages/home.md"
        i18n: true
        fields:
          - { label: "Avatar", name: "avatar", widget: "image", i18n: true }
          - { label: "Titre", name: "title", widget: "string", i18n: true }
          - {
              label: "Description",
              name: "description",
              widget: "string",
              i18n: true,
            }
          - label: "Social Network"
            name: "socialNetwork"
            widget: "list"
            i18n: true
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - {
                  label: "Logo",
                  name: "logo",
                  widget: "image",
                  choose_url: false,
                }
      - label: "À propos"
        name: "à propos"
        file: "content/pages/about.md"
        i18n: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - {
              label: "Presentation",
              name: "presentation",
              widget: "markdown",
              i18n: true,
            }
  - name: "global"
    label: "Global"
    i18n: true
    files:
      - label: "Menu"
        name: "menu"
        file: "content/global/menu.md"
        i18n: true
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            i18n: true
            fields:
              - { name: title, label: "Titre", widget: "string", i18n: true }
              - { name: url, label: "URL", widget: "string", i18n: true }
publish_mode: editorial_workflow
local_backend: true
