backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - { label: "Avatar", name: "avatar", widget: "image" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - label: "Social Network"
            name: "socialNetwork"
            widget: "list"
            fields:
              - { label: "Titre", name: "titre", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Logo", name: "logo", widget: "image" }
      - label: "About"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Presentation", name: "presentation", widget: "markdown" }
  - name: "global"
    label: "Global"
    files:
      - label: "Menu"
        name: "menu"
        file: "content/global/menu.md"
        fields:
          - label: "Items"
            name: "items"
            widget: "relation"
            collection: "pages"
            value_field: "{{slug}}"
            search_fields: ["title"]
            multiple: true
publish_mode: editorial_workflow
local_backend: true
